spring.application.name: spring-blueprints
blueprint-config:
  features:
    - GDPR-verification
    - preview-mode
  primary-cdn-provider: azure
  cdn-providers:
    azure:
      enabled: true
    tencent:
      enabled: true
    cloud-front:
      enabled: false
logging:
  level:
    org.blueprint.springblueprints.annotations.OnCdnProviderEnabledCondition: TRACE